package com.csstock.modle;



/**
 * DocumentType generated by MyEclipse Persistence Tools
 */


public class DocumentType  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer siteID;
     private String name;
     private String description;
     private String property1;
     private String property2;
     private String property3;
     private String property4;
     private String property5;
     private String property6;
     private String property7;
     private String property8;
     private String property9;
     private String property10;
     private String property11;
     private String property12;
     private String property13;
     private String property14;
     private String property15;
     private String property16;
     private String property17;
     private String property18;
     private String property19;
     private String property20;
     private String property21;
     private String property22;
     private String property23;
     private String property24;
     private String property25;


    // Constructors

    /** default constructor */
    public DocumentType() {
    }

	/** minimal constructor */
    public DocumentType(Integer id,  String name) {
        this.id = id;
        this.name = name;
    }
    
    /** full constructor */
    public DocumentType(Integer id, String name, String description, String property1, String property2, String property3, String property4, String property5, String property6, String property7, String property8, String property9, String property10, String property11, String property12, String property13, String property14, String property15, String property16, String property17, String property18, String property19, String property20, String property21, String property22, String property23, String property24, String property25) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.property1 = property1;
        this.property2 = property2;
        this.property3 = property3;
        this.property4 = property4;
        this.property5 = property5;
        this.property6 = property6;
        this.property7 = property7;
        this.property8 = property8;
        this.property9 = property9;
        this.property10 = property10;
        this.property11 = property11;
        this.property12 = property12;
        this.property13 = property13;
        this.property14 = property14;
        this.property15 = property15;
        this.property16 = property16;
        this.property17 = property17;
        this.property18 = property18;
        this.property19 = property19;
        this.property20 = property20;
        this.property21 = property21;
        this.property22 = property22;
        this.property23 = property23;
        this.property24 = property24;
        this.property25 = property25;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    //////////////////////////////
    
   

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getProperty1() {
        return this.property1;
    }
    
    public void setProperty1(String property1) {
        this.property1 = property1;
    }

    public String getProperty2() {
        return this.property2;
    }
    
    public void setProperty2(String property2) {
        this.property2 = property2;
    }

    public String getProperty3() {
        return this.property3;
    }
    
    public void setProperty3(String property3) {
        this.property3 = property3;
    }

    public String getProperty4() {
        return this.property4;
    }
    
    public void setProperty4(String property4) {
        this.property4 = property4;
    }

    public String getProperty5() {
        return this.property5;
    }
    
    public void setProperty5(String property5) {
        this.property5 = property5;
    }

    public String getProperty6() {
        return this.property6;
    }
    
    public void setProperty6(String property6) {
        this.property6 = property6;
    }

    public String getProperty7() {
        return this.property7;
    }
    
    public void setProperty7(String property7) {
        this.property7 = property7;
    }

    public String getProperty8() {
        return this.property8;
    }
    
    public void setProperty8(String property8) {
        this.property8 = property8;
    }

    public String getProperty9() {
        return this.property9;
    }
    
    public void setProperty9(String property9) {
        this.property9 = property9;
    }

    public String getProperty10() {
        return this.property10;
    }
    
    public void setProperty10(String property10) {
        this.property10 = property10;
    }

    public String getProperty11() {
        return this.property11;
    }
    
    public void setProperty11(String property11) {
        this.property11 = property11;
    }

    public String getProperty12() {
        return this.property12;
    }
    
    public void setProperty12(String property12) {
        this.property12 = property12;
    }

    public String getProperty13() {
        return this.property13;
    }
    
    public void setProperty13(String property13) {
        this.property13 = property13;
    }

    public String getProperty14() {
        return this.property14;
    }
    
    public void setProperty14(String property14) {
        this.property14 = property14;
    }

    public String getProperty15() {
        return this.property15;
    }
    
    public void setProperty15(String property15) {
        this.property15 = property15;
    }

    public String getProperty16() {
        return this.property16;
    }
    
    public void setProperty16(String property16) {
        this.property16 = property16;
    }

    public String getProperty17() {
        return this.property17;
    }
    
    public void setProperty17(String property17) {
        this.property17 = property17;
    }

    public String getProperty18() {
        return this.property18;
    }
    
    public void setProperty18(String property18) {
        this.property18 = property18;
    }

    public String getProperty19() {
        return this.property19;
    }
    
    public void setProperty19(String property19) {
        this.property19 = property19;
    }

    public String getProperty20() {
        return this.property20;
    }
    
    public void setProperty20(String property20) {
        this.property20 = property20;
    }

    public String getProperty21() {
        return this.property21;
    }
    
    public void setProperty21(String property21) {
        this.property21 = property21;
    }

    public String getProperty22() {
        return this.property22;
    }
    
    public void setProperty22(String property22) {
        this.property22 = property22;
    }

    public String getProperty23() {
        return this.property23;
    }
    
    public void setProperty23(String property23) {
        this.property23 = property23;
    }

    public String getProperty24() {
        return this.property24;
    }
    
    public void setProperty24(String property24) {
        this.property24 = property24;
    }

    public String getProperty25() {
        return this.property25;
    }
    
    public void setProperty25(String property25) {
        this.property25 = property25;
    }
}